### PR TITLE
catching FAILED status

### PR DESCRIPTION
**Pull request by marcstreeter**
provides exit case for loop tailing console.log

### CODE REVIEW

**Comment by doanac** [comment]
k - you found a weird bug in fioctl. Your fix actually doesn't "fix" - the javascript loop keeps going forever. It just happens to render correctly now. The API generally does report X-RUN-STATUS every time. 

The real fix looks like this:
~~~
diff --git a/gavel_ci/templates/console.html b/gavel_ci/templates/console.html
index 746a513..459e24f 100644
--- a/gavel_ci/templates/console.html
+++ b/gavel_ci/templates/console.html
@@ -42,6 +42,9 @@
         let messageContent = messageTail.join('\n');
         $(tailElement).text(`...\n${messageContent}`);
     };
+    var runComplete = function (status) {
+        return !status || status == "PASSED" || status == "FAILED" || status == "PROMOTED";
+    }
     var rawGet = function (url) {
         $.ajax(url, {
             dataType: "text",
@@ -56,7 +59,7 @@
                     } else {
                         updateLog(".");
                     }
-                } else if (!newStatus) { // finished
+                } else if (runComplete(newStatus)) { // finished
                     showDownload();
                     updateLog(data);
                     return;
~~~

I can't believe fioctl tailing is working most of the time. I see how *can* work, but I'm surprised that its usually worked. Here's how it all happens:

 https://github.com/foundriesio/jobserv/blob/master/jobserv/api/run.py#L298-L331

That function always returns a status header ... except for the very end were I detect a 'race condition'. That's the only way it won't set the header. JobServ should get fixed on line 331 to look like lines 308 and 309 so it gets set. However, this logic I've attached should be good for now.

I made a mock test of fioctl and can make it fail:
  https://hastebin.com/bafoxanaxa.cs

So we'll have to get the same patch applied to that as well.

**Comment by marcstreeter** [comment]
Cool -- it seems like ci.foundries.io works just a tad differently than
gavelci.us, no?  I don't recall ever getting the other status' you're
mentioning. I could have missed them though.  Thanks for fixing the code!

**Comment by marcstreeter** [comment]
oh - hah, I responded via email thinking you'd provided a separate commit to this. Did you want me to apply your changes or did you want to go ahead and just push them up?

**Comment by doanac** [comment]
> Cool -- it seems like ci.foundries.io works just a tad differently than
gavelci.us, no?  

I think its just pure timing. I'm shocked fioctl has ever worked consistently.

> Did you want me to apply your changes or did you want to go ahead and just push them up?

Why don't you push the changes to me? I wanted you to have a look over it and make sure the way I broke it up made sense

**Comment by marcstreeter** [comment]
sure -- I like what you did though. Especially compacting that conditional into a named function cleaned it up substantially

**Comment by marcstreeter** [comment]
oh my, I just realized that I put that check for the failed state in the wrong if conditional block. I'm glad you put yours in the right place. I've since removed it.

**Pull request merged**
